language: ruby
rvm:
- 2.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # 为 html-proofer 的安装加速

install:
  - bundle install

script:
#  - bundle exec jekyll algolia push
  - jekyll b

after_success:
  - cd ./_site
  - rm README Gemfile Gemfile.lock LICENSE
  - git init
  - git config user.name "Gyj1109 - Travis CI"
  - git config user.email "gaoyj1109@gmail.com"
  - git add .
  - git commit -m "Auto Build from Jekyll"
  - git push --force --quiet "https://${GitHub_TAKEN}@${GitHub_URL}" master:master
