language: ruby
rvm:
- 2.1

branches:
  only:
  - /pages-(.*)/ # 测试每一个以 "pages-" 开头的分支

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # 为 html-proofer 的安装加速

install:
  - npm install --save simple-jekyll-search
  - bundle install

script:
  - jekyll b

after_success:
  - cd ./_site
  - rm README Gemfile Gemfile.lock LICENSE
  - git init
  - git config user.name "Gyj1109 - Travis CI"
  - git config user.email "gaoyj1109@gmail.com"
  - git add .
  - git commit -m "Auto Build"
  - git push --force --quiet "https://${GitHub_TAKEN}@${GitHub_URL}" master:master
